name: Форматирование кода с помощью Black

on:
  push:  # Запускается при каждом пуше
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  format:
    name: Форматирование с Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Проверка кода из репозитория
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Укажите нужную версию Python
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install black  # Установка black
      - name: Форматирование кода
        run: black .  # Форматирует все файлы в текущем каталоге
